Tags instead of Categories
astrolicious/astro-tips.dev pull request #155
Opened 2024-06-12 18:29 UTC by hkbertoson

This is the start of working on #146 for using Tags instead of Categories.

2024-06-13 06:08 UTC, alexanderniebuhr commented on src/components/Tags.astro
> +</div>
Could we add a list of all resources to this page, which can be filtered if someone clicks on one of the tags from the list?

2024-06-17 14:55 UTC, alexanderniebuhr commented on src/components/Tags.astro
> +</div>
After looking at this myself, it is not that easy.. Need to investigate further, will update later.

2024-06-17 14:55 UTC, alexanderniebuhr requested changes
Blocking, until we figure out how to implement filtering..

2024-06-17 15:53 UTC, BryceRussell commented
Idea for filtering server-side that is compatible with Starlight/`hybrid` mode:

1. Create a SSR partial route with `export const prerender = false;` and `export const partial = true`
2. Author partial route to render a filtered version of the list using data from the request (JSON, query parameters, form data, etc)
3. Filter the list by fetching the partial client side and swapping the old list with the new filtered list

2024-06-17 16:54 UTC, hkbertoson commented
I think query parameters would be the best option. Then that would allow users to share a URL with the filters.

2024-06-18 06:10 UTC, alexanderniebuhr commented
> I think query parameters would be the best option. Then that would allow users to share a URL with the filters.

We looked at that during the call, it doesn't work, since Starlight is prerendered. And I don't want to do some workarounds with inline scripts. But as @BryceRussell we could use some "island" partial solution. 

Another idea would be to always inline all items inside the HTML, and only do client-side filtering, should be fast enough for a long time too.

2024-06-19 03:01 UTC, OliverSpeir commented
@HiDeoo Any suggestions on this?

2024-06-21 06:11 UTC, alexanderniebuhr commented
> _https://github.com/astrolicious/astro-tips.dev/pull/155#issuecomment-2177454335_: @HiDeoo Any suggestions on this?

It was answered on Discord, which can be found [here](https://discord.com/channels/1217527207467946087/1217544238397526016/1252894745991315507).

2024-07-09 12:28 UTC, florian-lefebvre commented on astro.config.ts
> +						{ slug: 'resources/educational' },
Do we need this anymore? I'd say tags should replace the current system

2024-07-09 12:28 UTC, florian-lefebvre commented on src/content/config.ts
> +		tags: z.array(z.string()),
Maybe we want to use a reference to a new `tags` collection to have proper display names?

2024-07-09 12:28 UTC, florian-lefebvre commented on src/content/resources/astro-db-migrating-analytics-postgres.json
let's get rid of the category then?

2024-07-09 12:28 UTC, florian-lefebvre commented on src/content/docs/resources/tags.mdx
I think this page should be removed?

2024-07-15 12:41 UTC, alexanderniebuhr approved these changes

2024-07-15 13:59 UTC, florian-lefebvre commented on src/content/config.ts
> +		tags: z.array(z.string()),
in a follow up pr

2024-07-15 14:47 UTC, merged