Adds basic GSAP recipe!
astrolicious/astro-tips.dev pull request #24
Opened 2024-03-13 17:08 UTC by jdtjenkins

Don't know if it needs to be more fancy than this! This should be enough for most people to understand how to add gsap to their project.

2024-03-13 17:38 UTC, florian-lefebvre requested changes
Can you add a link at the end to the gsap docs?

2024-03-13 17:38 UTC, florian-lefebvre commented on src/content/docs/recipes/gsap.mdx
> +import { gsap} from "gsap";
```suggestion
import { gsap } from "gsap";
```

2024-03-13 17:46 UTC, Adammatthiesen reviewed
reference link to their docs as @florian-lefebvre said and the other small changes then your good!

2024-03-13 17:54 UTC, Adammatthiesen approved these changes
Perfect 🎉

2024-03-13 18:17 UTC, at-the-vr reviewed
Got couple of suggestions, LGTM 👍

2024-03-13 19:32 UTC, florian-lefebvre commented on src/content/docs/recipes/gsap.mdx
> +        ```sh
i don't think biome supports md/mdx just yet but formatting is an important topic for sure

2024-03-13 21:39 UTC, jdtjenkins commented on src/content/docs/recipes/gsap.mdx
> +        ```sh
Ah I actually didn't realise that's why it was happening 😂 I don't use starlight much!

I thought the code component handled that for you 🤔 I feel like we don't want to just remove the indent for that one line in the code.

Does anyone have a better idea for this?

2024-03-13 22:11 UTC, VoxelMC commented on src/content/docs/recipes/gsap.mdx
> +        ```sh
Honestly, in docs we just have it unindented!

E.g.
````jsx
<PackageManagerTabs>
  <Fragment slot="npm">
  ```shell
  npm install --save-dev prettier prettier-plugin-astro
  ```
  </Fragment>
  <Fragment slot="pnpm">
  ```shell
  pnpm add -D prettier prettier-plugin-astro
  ```
  </Fragment>
  <Fragment slot="yarn">
  ```shell
  yarn add --dev prettier prettier-plugin-astro
  ```
  </Fragment>
</PackageManagerTabs>
````

I don't mind it, personally!

2024-03-14 03:28 UTC, at-the-vr commented on src/content/docs/recipes/gsap.mdx
> +        ```sh
I will resolve this conversation (really trivial)

2024-03-14 07:30 UTC, florian-lefebvre approved these changes

2024-03-14 07:31 UTC, merged

2024-03-14 09:27 UTC, jdtjenkins commented on src/content/docs/recipes/gsap.mdx
> +        ```sh
Ahhhhhhhhh I see! Yeah my bad

2024-03-14 10:14 UTC, florian-lefebvre commented on src/content/docs/recipes/gsap.mdx
> +        ```sh
I fixed it for you ;)